# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "My Client ID"
name = "My Shopify APP Name"
handle = "my-store-manager-1"
application_url = "https://car-roulette-parker-leader.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "My Store URL"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://car-roulette-parker-leader.trycloudflare.com/auth/callback",
  "https://car-roulette-parker-leader.trycloudflare.com/auth/shopify/callback",
  "https://car-roulette-parker-leader.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
